services:
  - type: web
    name: airfare-price-index
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONIOENCODING
        value: "utf-8"
